# Generated by Django 2.2.4 on 2019-08-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
